layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  youtube: wikyprash
  twitter: wikyprash
  linkedin: wikyprash
  stackoverflow: 12747871/wikyprash
  hackerrank: wikyprash
  facebook: wikyprash
  instagram: wikyprash
  medium: wikyprash
  telegram: wikyprash
  dribbble: wikyprash
  behance: wikyprash
#   vk: wikyprash
#   keybase: wikyprash
#   mastodon: your_username
#   unsplash: your_username
#   website: http://your_website_url
  
